import type { ConverterType } from '../hooks/useConverter';
import {
  encodeBase64, decodeBase64,
  encodeBase32, decodeBase32,
  encodeUrl, decodeUrl,
  encodeHtml, decodeHtml,
  encodeUnicode, decodeUnicode,
  encodeHex, decodeHex,
  encodeBinary, decodeBinary,
  encodeOctal, decodeOctal,
  encodeRot13, decodeRot13,
  encodeMorse, decodeMorse,
  encodeAscii, decodeAscii,
  hashSha256, hashSha512, hashSha1,
  encodeTimestamp, decodeTimestamp,
  encodeColor,
  encodeNumberBase,
  generateLoremIpsum,
  textStatistics,
  validateJson, validateXml,
  formatCsv, formatMarkdown, formatSql,
  decodeJwt,
  encodeUuid,
  validateEmail, validateIpAddress,
  testRegex, parseCron, parseUrl,
  jsonToYaml, yamlToJson,
  convertStringCase,
  escapeString, unescapeString,
  generatePassword,
  sortLines, dedupeLines,
  slugify,
  markdownToHtml,
  minifyJson,
  generatePlaceholderUrl,
} from './encodingUtils';

export const converters: ConverterType[] = [
  // ─── Encoding ────────────────────────────────────────────────────────────
  {
    name: 'Base64',
    slug: 'base64-encoder-decoder',
    encode: encodeBase64,
    decode: decodeBase64,
    description: 'Encode and decode text using Base64. Supports full Unicode via UTF-8.',
    longDescription: 'Free online Base64 encoder and decoder tool. Convert text, files, and binary data to and from Base64 encoding with full Unicode/UTF-8 support. Base64 is commonly used for encoding binary data in email attachments (MIME), data URIs in HTML/CSS, storing complex data in JSON and XML, and API authentication tokens. All processing happens client-side in your browser for complete privacy.',
    keywords: ['base64 encode', 'base64 decode', 'base64 converter', 'text to base64', 'base64 to text', 'base64 online', 'utf-8 base64'],
    category: 'encoding',
  },
  {
    name: 'Base32',
    slug: 'base32-encoder-decoder',
    encode: encodeBase32,
    decode: decodeBase32,
    description: 'RFC 4648 Base32 encoding. Case-insensitive and avoids ambiguous characters.',
    longDescription: 'Free online Base32 encoder and decoder following RFC 4648. Base32 uses a case-insensitive alphabet of A-Z and 2-7, making it ideal for systems that are case-insensitive or need to avoid visually ambiguous characters. Commonly used in TOTP/HOTP two-factor authentication, file systems, and DNS labels.',
    keywords: ['base32 encode', 'base32 decode', 'rfc 4648', 'base32 converter', 'totp base32'],
    category: 'encoding',
  },
  {
    name: 'URL Encoding',
    slug: 'url-encoder-decoder',
    encode: encodeUrl,
    decode: decodeUrl,
    description: 'Percent-encode special characters for safe use in URLs and query strings.',
    longDescription: 'Free online URL encoder and decoder tool. Percent-encode special characters like spaces, ampersands, and unicode characters for safe inclusion in URLs, query strings, and form data. Essential for building API requests, creating shareable links, and debugging URL parameters. Handles both encodeURIComponent and full URL encoding.',
    keywords: ['url encode', 'url decode', 'percent encoding', 'urlencode online', 'encode url string', 'query string encoder'],
    category: 'encoding',
  },
  {
    name: 'HTML Entities',
    slug: 'html-entity-encoder-decoder',
    encode: encodeHtml,
    decode: decodeHtml,
    description: 'Convert special characters to HTML entities and back for safe rendering.',
    longDescription: 'Free online HTML entity encoder and decoder. Convert special characters like <, >, &, and quotes to their HTML entity equivalents to prevent XSS attacks and ensure safe rendering in web pages. Essential for sanitizing user input, embedding code snippets in HTML, and working with special characters in web content.',
    keywords: ['html entities', 'html encode', 'html decode', 'html special characters', 'html escape', 'xss prevention'],
    category: 'encoding',
  },
  {
    name: 'Unicode Escape',
    slug: 'unicode-escape-converter',
    encode: encodeUnicode,
    decode: decodeUnicode,
    description: 'Convert non-ASCII characters to \\u{XXXX} escape sequences and back.',
    longDescription: 'Free online Unicode escape sequence converter. Convert text with non-ASCII characters (emojis, CJK, accented letters) to JavaScript/JSON \\u{XXXX} escape sequences and back. Useful for embedding international characters in source code, debugging encoding issues, and working with Unicode in APIs.',
    keywords: ['unicode escape', 'unicode converter', 'unicode to text', 'text to unicode', 'javascript unicode', 'unicode escape sequence'],
    category: 'encoding',
  },
  {
    name: 'Hex',
    slug: 'hex-encoder-decoder',
    encode: encodeHex,
    decode: decodeHex,
    description: 'Convert text to space-separated hexadecimal bytes and back.',
    longDescription: 'Free online hexadecimal encoder and decoder. Convert text to hex bytes and back. Hexadecimal encoding is widely used in programming, debugging, network analysis, color codes, and cryptography. View the raw byte representation of any text including UTF-8 multi-byte characters.',
    keywords: ['hex encoder', 'hex decoder', 'text to hex', 'hex to text', 'hexadecimal converter', 'hex string'],
    category: 'encoding',
  },
  {
    name: 'Binary',
    slug: 'binary-text-converter',
    encode: encodeBinary,
    decode: decodeBinary,
    description: 'Convert text to 8-bit binary representation and back.',
    longDescription: 'Free online binary to text converter. Convert text to 8-bit binary representation and decode binary strings back to readable text. Useful for learning about character encoding, understanding how computers store text data, and working with low-level data representation.',
    keywords: ['binary converter', 'text to binary', 'binary to text', 'binary translator', 'binary code converter', '8-bit binary'],
    category: 'encoding',
  },
  {
    name: 'Octal',
    slug: 'octal-converter',
    encode: encodeOctal,
    decode: decodeOctal,
    description: 'Convert text to octal byte representation and back.',
    longDescription: 'Free online octal converter tool. Convert text to octal (base-8) byte representation and decode octal values back to text. Octal is used in Unix file permissions, C/C++ escape sequences, and historical computing contexts.',
    keywords: ['octal converter', 'text to octal', 'octal to text', 'base 8 converter', 'octal encoding'],
    category: 'encoding',
  },
  {
    name: 'ROT13',
    slug: 'rot13-cipher',
    encode: encodeRot13,
    decode: decodeRot13,
    description: 'Apply ROT13 letter substitution cipher. Letters shift 13 positions; self-reversing.',
    longDescription: 'Free online ROT13 encoder and decoder. ROT13 is a simple letter substitution cipher that shifts each letter 13 positions in the alphabet. It is self-reversing — encoding and decoding use the same operation. Commonly used on forums and social media to hide spoilers, puzzle solutions, and mild content behind an easily reversible cipher.',
    keywords: ['rot13', 'rot13 encoder', 'rot13 decoder', 'rot13 cipher', 'caesar cipher', 'letter substitution'],
    category: 'encoding',
  },
  {
    name: 'Morse Code',
    slug: 'morse-code-translator',
    encode: encodeMorse,
    decode: decodeMorse,
    description: 'Convert text to International Morse Code using dots and dashes.',
    longDescription: 'Free online Morse code translator. Convert text to International Morse Code (dots and dashes) and decode Morse code back to text. Supports letters A-Z, digits 0-9, and common punctuation. Great for learning Morse code, amateur radio, and educational purposes.',
    keywords: ['morse code translator', 'text to morse code', 'morse code to text', 'morse code converter', 'morse code encoder', 'international morse code'],
    category: 'encoding',
  },
  {
    name: 'ASCII / Decimal',
    slug: 'ascii-decimal-converter',
    encode: encodeAscii,
    decode: decodeAscii,
    description: 'Convert characters to their decimal ASCII/Unicode code points and back.',
    longDescription: 'Free online ASCII and decimal code point converter. Convert characters to their decimal ASCII or Unicode code point values, and decode numeric values back to characters. Useful for debugging character encoding issues, working with ASCII art, and understanding character sets.',
    keywords: ['ascii converter', 'ascii to decimal', 'decimal to ascii', 'character code', 'ascii table', 'unicode code point'],
    category: 'encoding',
  },

  // ─── Formatting ──────────────────────────────────────────────────────────
  {
    name: 'JSON Formatter',
    slug: 'json-formatter-validator',
    validate: validateJson,
    description: 'Validate and pretty-print JSON with proper indentation.',
    longDescription: 'Free online JSON formatter and validator. Paste your JSON and instantly validate its syntax and pretty-print it with proper indentation. Quickly catch syntax errors, missing brackets, and formatting issues. Essential for debugging API responses, configuration files, and data payloads.',
    keywords: ['json formatter', 'json validator', 'json beautifier', 'json pretty print', 'format json online', 'json lint', 'validate json'],
    category: 'format',
  },
  {
    name: 'XML Formatter',
    slug: 'xml-formatter-validator',
    validate: validateXml,
    description: 'Validate and format XML documents with indentation.',
    longDescription: 'Free online XML formatter and validator. Validate XML document syntax and format it with proper indentation for readability. Useful for working with SOAP APIs, RSS feeds, SVG files, configuration files, and any XML-based data format.',
    keywords: ['xml formatter', 'xml validator', 'xml beautifier', 'xml pretty print', 'format xml online', 'xml lint'],
    category: 'format',
  },
  {
    name: 'CSV Formatter',
    slug: 'csv-formatter',
    validate: formatCsv,
    description: 'Parse and align CSV data into neatly formatted columns.',
    longDescription: 'Free online CSV formatter tool. Parse comma-separated values and align them into neatly formatted, easy-to-read columns. Handles quoted fields and various CSV dialects. Perfect for reviewing spreadsheet exports, data migration files, and database dumps.',
    keywords: ['csv formatter', 'csv viewer', 'format csv', 'csv to table', 'csv beautifier', 'csv parser'],
    category: 'format',
  },
  {
    name: 'Markdown Formatter',
    slug: 'markdown-formatter',
    validate: formatMarkdown,
    description: 'Clean up markdown with consistent spacing around headers, lists, and paragraphs.',
    longDescription: 'Free online Markdown formatter. Clean up and normalize your Markdown documents with consistent spacing around headers, lists, and paragraphs. Ensures proper formatting for GitHub READMEs, documentation, blog posts, and other Markdown content.',
    keywords: ['markdown formatter', 'format markdown', 'markdown beautifier', 'markdown lint', 'clean markdown'],
    category: 'format',
  },
  {
    name: 'SQL Formatter',
    slug: 'sql-formatter',
    validate: formatSql,
    description: 'Format SQL queries with uppercase keywords and proper line breaks.',
    longDescription: 'Free online SQL formatter and beautifier. Format SQL queries with uppercase keywords, proper indentation, and line breaks for readability. Supports SELECT, INSERT, UPDATE, DELETE, JOIN, and other common SQL statements. Essential for code reviews, documentation, and debugging complex queries.',
    keywords: ['sql formatter', 'sql beautifier', 'format sql', 'sql pretty print', 'sql format online', 'sql indent'],
    category: 'format',
  },
  {
    name: 'JSON to YAML',
    slug: 'json-yaml-converter',
    encode: jsonToYaml,
    decode: yamlToJson,
    description: 'Convert between JSON and YAML formats. Encode: JSON to YAML. Decode: YAML to JSON.',
    longDescription: 'Free online JSON to YAML converter and YAML to JSON converter. Seamlessly convert between these two popular data serialization formats. JSON is common in APIs and JavaScript, while YAML is preferred for configuration files (Docker Compose, Kubernetes, CI/CD pipelines). Convert in both directions instantly.',
    keywords: ['json to yaml', 'yaml to json', 'json yaml converter', 'yaml converter', 'json converter', 'data format converter'],
    category: 'format',
  },

  // ─── Cryptography & Hashing ──────────────────────────────────────────────
  {
    name: 'JWT Decoder',
    slug: 'jwt-decoder',
    decode: (input: string) => {
      const result = decodeJwt(input);
      if (result.error) throw new Error(result.error);
      return JSON.stringify({ header: result.header, payload: result.payload }, null, 2);
    },
    description: 'Decode JWT tokens to inspect header and payload claims (signature not verified).',
    longDescription: 'Free online JWT (JSON Web Token) decoder. Paste a JWT and instantly decode its header and payload claims without verifying the signature. Inspect token expiration, issuer, audience, roles, and custom claims. Essential for debugging authentication flows, OAuth2, and API authorization.',
    keywords: ['jwt decoder', 'jwt token decoder', 'decode jwt', 'json web token', 'jwt debugger', 'jwt parser', 'jwt viewer'],
    category: 'crypto',
  },
  {
    name: 'UUID Generator',
    slug: 'uuid-generator',
    encode: encodeUuid,
    description: 'Generate cryptographically random UUID v4 identifiers.',
    longDescription: 'Free online UUID v4 generator using the Web Crypto API for cryptographically secure random values. UUID (Universally Unique Identifier) v4 generates random 128-bit identifiers. Used as database primary keys, session tokens, request IDs, and unique resource identifiers in distributed systems.',
    keywords: ['uuid generator', 'uuid v4', 'generate uuid', 'random uuid', 'guid generator', 'unique id generator'],
    category: 'crypto',
  },
  {
    name: 'SHA-256 Hash',
    slug: 'sha256-hash-generator',
    encode: hashSha256 as (input: string) => string,
    description: 'Generate SHA-256 cryptographic hash digest of text using Web Crypto API.',
    longDescription: 'Free online SHA-256 hash generator. Compute the SHA-256 cryptographic hash of any text using the browser\'s native Web Crypto API. SHA-256 is part of the SHA-2 family and is widely used for data integrity verification, digital signatures, password hashing, blockchain, and certificate validation.',
    keywords: ['sha256', 'sha-256', 'sha256 hash', 'sha256 generator', 'sha256 online', 'hash generator', 'sha2'],
    category: 'crypto',
  },
  {
    name: 'SHA-512 Hash',
    slug: 'sha512-hash-generator',
    encode: hashSha512 as (input: string) => string,
    description: 'Generate SHA-512 cryptographic hash digest of text using Web Crypto API.',
    longDescription: 'Free online SHA-512 hash generator. Compute the SHA-512 cryptographic hash of any text using the browser\'s native Web Crypto API. SHA-512 produces a 512-bit (64-byte) hash and is used for high-security applications, digital signatures, and data integrity verification.',
    keywords: ['sha512', 'sha-512', 'sha512 hash', 'sha512 generator', 'sha512 online', 'hash generator'],
    category: 'crypto',
  },
  {
    name: 'SHA-1 Hash',
    slug: 'sha1-hash-generator',
    encode: hashSha1 as (input: string) => string,
    description: 'Generate SHA-1 hash digest. Note: SHA-1 is deprecated for security use.',
    longDescription: 'Free online SHA-1 hash generator. Compute the SHA-1 hash of any text. While SHA-1 is deprecated for security-critical applications due to known collision vulnerabilities, it is still used for checksums, git commit hashes, and legacy system compatibility.',
    keywords: ['sha1', 'sha-1', 'sha1 hash', 'sha1 generator', 'sha1 online', 'sha1 checksum'],
    category: 'crypto',
  },

  // ─── Developer Tools ─────────────────────────────────────────────────────
  {
    name: 'Timestamp Converter',
    slug: 'unix-timestamp-converter',
    encode: encodeTimestamp,
    decode: decodeTimestamp,
    description: 'Convert dates to Unix timestamps (encode) or timestamps to dates (decode).',
    longDescription: 'Free online Unix timestamp converter. Convert human-readable dates to Unix epoch timestamps (seconds since January 1, 1970) and vice versa. Essential for working with APIs, databases, logging systems, and any application that uses epoch time.',
    keywords: ['unix timestamp', 'timestamp converter', 'epoch converter', 'date to timestamp', 'timestamp to date', 'epoch time'],
    category: 'devtools',
  },
  {
    name: 'Color Converter',
    slug: 'color-converter',
    encode: encodeColor,
    description: 'Convert between hex, RGB, and HSL color formats. Enter any supported format.',
    longDescription: 'Free online color format converter. Convert colors between HEX (#ff0000), RGB (rgb(255,0,0)), and HSL (hsl(0,100%,50%)) formats instantly. Essential for web development, CSS styling, design systems, and translating colors between different tools and platforms.',
    keywords: ['color converter', 'hex to rgb', 'rgb to hex', 'hsl converter', 'color format', 'css color converter', 'hex color'],
    category: 'devtools',
  },
  {
    name: 'Number Base',
    slug: 'number-base-converter',
    encode: encodeNumberBase,
    description: 'Convert numbers between decimal, hex (0x), binary (0b), and octal (0o).',
    longDescription: 'Free online number base converter. Convert numbers between decimal (base 10), hexadecimal (base 16, 0x prefix), binary (base 2, 0b prefix), and octal (base 8, 0o prefix). Essential for programming, debugging, and understanding computer number representation.',
    keywords: ['number base converter', 'decimal to hex', 'hex to binary', 'binary to decimal', 'octal converter', 'base converter', 'radix converter'],
    category: 'devtools',
  },
  {
    name: 'URL Parser',
    slug: 'url-parser',
    validate: parseUrl,
    description: 'Break down a URL into its components: protocol, host, path, query params, and more.',
    longDescription: 'Free online URL parser and analyzer. Break down any URL into its individual components: protocol, hostname, port, pathname, query parameters, hash fragment, and origin. Useful for debugging API endpoints, analyzing links, and understanding URL structure.',
    keywords: ['url parser', 'parse url', 'url analyzer', 'url breakdown', 'query string parser', 'url components'],
    category: 'devtools',
  },
  {
    name: 'Regex Tester',
    slug: 'regex-tester',
    validate: testRegex,
    description: 'Test regex patterns. Format: /pattern/flags then --- then test string on separate lines.',
    longDescription: 'Free online regular expression tester. Test regex patterns against text strings and see all matches, capture groups, and named groups. Supports JavaScript regex syntax with global, case-insensitive, multiline, and other flags. Essential for building and debugging regex patterns.',
    keywords: ['regex tester', 'regex online', 'regular expression tester', 'regex debugger', 'regex validator', 'test regex', 'regex matcher'],
    category: 'devtools',
  },
  {
    name: 'Cron Parser',
    slug: 'cron-expression-parser',
    validate: parseCron,
    description: 'Parse and explain cron expressions. Enter 5 or 6 space-separated fields.',
    longDescription: 'Free online cron expression parser and explainer. Enter a cron expression and get a human-readable description of what each field means and when the job will run. Supports standard 5-field and extended 6-field (with year) cron formats used by crontab, Kubernetes CronJobs, and CI/CD schedulers.',
    keywords: ['cron parser', 'cron expression', 'crontab', 'cron schedule', 'cron explainer', 'cron generator', 'cron job'],
    category: 'devtools',
  },

  // ─── Generators & Validators ─────────────────────────────────────────────
  {
    name: 'Lorem Ipsum',
    slug: 'lorem-ipsum-generator',
    encode: generateLoremIpsum,
    description: 'Generate placeholder text. Enter a number (1-50) for paragraph count.',
    longDescription: 'Free online Lorem Ipsum placeholder text generator. Generate 1 to 50 paragraphs of classic Lorem Ipsum dummy text for mockups, wireframes, and design prototypes. The standard filler text used by designers and developers worldwide since the 1500s.',
    keywords: ['lorem ipsum generator', 'placeholder text', 'dummy text', 'filler text', 'lorem ipsum', 'lipsum generator'],
    category: 'misc',
  },
  {
    name: 'Text Statistics',
    slug: 'text-statistics-counter',
    encode: textStatistics,
    description: 'Count characters, words, lines, sentences, and analyze letter frequency.',
    longDescription: 'Free online text statistics and word counter tool. Count characters (with and without spaces), words, lines, sentences, and paragraphs. Also analyzes letter frequency distribution. Useful for checking essay word counts, analyzing text composition, and content optimization.',
    keywords: ['word counter', 'character counter', 'text statistics', 'word count', 'letter frequency', 'text analyzer'],
    category: 'misc',
  },
  {
    name: 'Email Validator',
    slug: 'email-validator',
    validate: validateEmail,
    description: 'Check if an email address has a valid format.',
    longDescription: 'Free online email address format validator. Check if an email address follows the standard format with proper local part, @ symbol, and domain. Validates against common formatting rules for quick syntax checking before sending.',
    keywords: ['email validator', 'validate email', 'email checker', 'email format', 'email syntax check'],
    category: 'misc',
  },
  {
    name: 'IP Address Validator',
    slug: 'ip-address-validator',
    validate: validateIpAddress,
    description: 'Validate IPv4 and IPv6 address formats.',
    longDescription: 'Free online IP address validator. Check if an IP address is a valid IPv4 (e.g., 192.168.1.1) or IPv6 (e.g., 2001:0db8::1) format. Essential for network configuration, firewall rules, and server administration.',
    keywords: ['ip validator', 'ip address validator', 'validate ip', 'ipv4 validator', 'ipv6 validator', 'ip address checker'],
    category: 'misc',
  },

  // ─── Text Tools ─────────────────────────────────────────────────────────
  {
    name: 'String Case Converter',
    slug: 'string-case-converter',
    encode: convertStringCase,
    description: 'Convert text to camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, and more.',
    longDescription: 'Free online string case converter. Convert text between camelCase, PascalCase, snake_case, kebab-case, CONSTANT_CASE, Title Case, dot.case, and path/case in one click. Essential for naming conventions when switching between programming languages, frameworks, CSS classes, and database columns.',
    keywords: ['case converter', 'camelcase', 'snake case', 'kebab case', 'pascal case', 'string case', 'naming convention converter'],
    category: 'devtools',
  },
  {
    name: 'Backslash Escape',
    slug: 'string-escape-unescape',
    encode: escapeString,
    decode: unescapeString,
    description: 'Escape special characters (\\n, \\t, quotes) for use in code strings, or unescape them back.',
    longDescription: 'Free online string escape and unescape tool. Escape special characters like newlines (\\n), tabs (\\t), backslashes, and quotes for use in programming strings, JSON, and configuration files. Also unescape escaped strings back to their original form.',
    keywords: ['string escape', 'string unescape', 'escape characters', 'backslash escape', 'json escape', 'unescape string'],
    category: 'encoding',
  },
  {
    name: 'Password Generator',
    slug: 'password-generator',
    encode: generatePassword,
    description: 'Generate a cryptographically secure random password. Enter desired length (default 16).',
    longDescription: 'Free online secure password generator. Generate cryptographically strong random passwords using the Web Crypto API. Includes uppercase, lowercase, digits, and symbols with guaranteed character variety. Shows password entropy in bits for security assessment.',
    keywords: ['password generator', 'random password', 'secure password', 'strong password generator', 'password creator', 'crypto random password'],
    category: 'crypto',
  },
  {
    name: 'Line Sort & Dedupe',
    slug: 'line-sort-dedupe',
    encode: sortLines,
    decode: dedupeLines,
    description: 'Encode: sort lines alphabetically. Decode: remove duplicate lines.',
    longDescription: 'Free online line sort and deduplication tool. Sort lines alphabetically or remove duplicate lines from text. Perfect for cleaning up lists, processing log files, organizing data, and preparing CSV/text files for comparison.',
    keywords: ['sort lines', 'remove duplicates', 'dedupe lines', 'line sorter', 'unique lines', 'remove duplicate lines'],
    category: 'devtools',
  },
  {
    name: 'Slugify',
    slug: 'slugify-url-slug-generator',
    encode: slugify,
    description: 'Convert text to a URL-friendly slug (lowercase, hyphens, no special chars).',
    longDescription: 'Free online slug generator. Convert titles, headings, or any text into URL-friendly slugs. Handles Unicode normalization, strips diacritics, removes special characters, and converts spaces to hyphens. Essential for creating SEO-friendly URLs for blog posts, articles, and web pages.',
    keywords: ['slugify', 'slug generator', 'url slug', 'seo url', 'url friendly', 'permalink generator'],
    category: 'devtools',
  },
  {
    name: 'Markdown to HTML',
    slug: 'markdown-to-html-converter',
    encode: markdownToHtml,
    description: 'Convert Markdown text to HTML. Supports headers, bold, italic, code, links, and lists.',
    longDescription: 'Free online Markdown to HTML converter. Convert Markdown syntax to clean HTML output. Supports headers (h1-h6), bold, italic, inline code, code blocks, links, images, blockquotes, ordered and unordered lists, and horizontal rules. Perfect for previewing Markdown content and generating HTML for web pages.',
    keywords: ['markdown to html', 'md to html', 'markdown converter', 'markdown renderer', 'convert markdown', 'markdown html'],
    category: 'format',
  },
  {
    name: 'JSON Minifier',
    slug: 'json-minifier',
    encode: minifyJson,
    description: 'Minify JSON by removing all whitespace. Shows bytes saved.',
    longDescription: 'Free online JSON minifier and compressor. Remove all unnecessary whitespace from JSON data to reduce file size. Shows the number of characters saved and percentage reduction. Ideal for optimizing API payloads, reducing bandwidth, and preparing JSON for production environments.',
    keywords: ['json minifier', 'minify json', 'json compressor', 'compact json', 'json compress', 'reduce json size'],
    category: 'format',
  },
  {
    name: 'Placeholder Image',
    slug: 'placeholder-image-generator',
    encode: generatePlaceholderUrl,
    description: 'Generate placeholder image URLs. Enter dimensions like "300x200" or just "400".',
    longDescription: 'Free online placeholder image URL generator. Generate placeholder image URLs from popular services like placehold.co and picsum.photos. Get ready-to-use HTML img tags, Markdown image syntax, and CSS background properties for your mockups, wireframes, and prototypes.',
    keywords: ['placeholder image', 'placeholder image generator', 'dummy image', 'placeholder url', 'image placeholder', 'mockup image'],
    category: 'devtools',
  },
];
